const ACTION_TYPES = {
  IS_USER_ACTIVE: "IS_USER_ACTIVE",
  TICKET_DATA: "TICKET_DATA",
  USER_INFO: "USER_INFO",
  CITIES_INFO: "CITIES_INFO",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SEAT_LIST: "SEAT_LIST",
  ADD_SEAT_LIST: "ADD_SEAT_LIST",
  REMOVE_SEAT_LIST: "REMOVE_SEAT_LIST",
};
export default ACTION_TYPES;
