export const fromData = [
  { label: "Nereden ?", value: "" },
  { label: "İstanbul", value: 1 },
  { label: "Sinop", value: 2 },
  { label: "Antalya", value: 3 },
  { label: "Adıyaman", value: 4 },
];

export const toData = [
  { label: "Nereye ?", value: "" },
  { label: "İstanbul", value: 1 },
  { label: "Sinop", value: 2 },
  { label: "Antalya", value: 3 },
  { label: "Adıyaman", value: 4 },
];

export const voyageData = [
  {
    id: 1,
    from: "İstanbul",
    to: "Sinop",
    startDate: "2023-04-28T12:23:00.000Z",
    isroundtrip: false,
    price: 100,
    emptySeat: 19,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 2,
    from: "İstanbul",
    to: "Sinop",
    startDate: "2023-04-28T12:23:00.000Z",
    isroundtrip: false,
    price: 250,
    emptySeat: 16,
    time: "12:30",
    company: "Metro",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 3,
    from: "İstanbul",
    to: "Sinop",
    startDate: "2023-04-28T12:23:00.000Z",
    isroundtrip: false,
    price: 350,
    emptySeat: 15,
    time: "16:30",
    company: "Pamukkae",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 4,
    from: "Sinop",
    to: "İstanbul",
    startDate: "2023-05-28T12:23:00.000Z",
    isroundtrip: false,
    price: 120,
    emptySeat: 15,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 5,
    from: "Sinop",
    to: "İstanbul",
    startDate: "2023-05-28T12:23:00.000Z",
    isroundtrip: false,
    price: 120,
    emptySeat: 15,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 6,
    from: "Sinop",
    to: "İstanbul",
    startDate: "2023-05-28T12:23:00.000Z",
    isroundtrip: false,
    price: 120,
    emptySeat: 15,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 7,
    from: "İstanbul",
    to: "Antalya",
    startDate: "2023-05-20T12:23:00.000Z",
    isroundtrip: false,
    price: 140,
    emptySeat: 19,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
    ],
  },
  {
    id: 8,
    from: "Antalya",
    to: "İstanbul",
    startDate: "2023-05-20T12:23:00.000Z",
    isroundtrip: false,
    price: 180,
    emptySeat: 15,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 9,
    from: "İstanbul",
    to: "Adıyaman",
    startDate: "2023-05-20T12:23:00.000Z",
    isroundtrip: false,
    price: 350,
    time: "12:00",
    emptySeat: 12,
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 10,
    from: "Adıyaman",
    to: "İstanbul",
    startDate: "2023-05-27T12:23:00.000Z",
    isroundtrip: false,
    price: 200,
    emptySeat: 18,
    time: "12:00",
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 11,
    from: "Sinop",
    to: "Antalya",
    startDate: "2023-05-27T12:23:00.000Z",
    isroundtrip: false,
    price: 430,
    time: "12:00",
    emptySeat: 15,
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
  {
    id: 12,
    from: "Antalya",
    to: "Sinop",
    startDate: "2023-05-27T12:23:00.000Z",
    isroundtrip: false,
    price: 170,
    time: "12:00",
    emptySeat: 15,
    company: "Kamil Koç",
    fullSeat: [
      { seatNumber: 1, seatType: "booked" },
      { seatNumber: 3, seatType: "booked" },
      { seatNumber: 5, seatType: "booked" },
      { seatNumber: 7, seatType: "booked" },
      { seatNumber: 11, seatType: "women" },
      { seatNumber: 17, seatType: "booked" },
      { seatNumber: 16, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 22, seatType: "women" },
      { seatNumber: 23, seatType: "women" },
      { seatNumber: 14, seatType: "booked" },
      { seatNumber: 17, seatType: "women" },
      { seatNumber: 29, seatType: "women" },
    ],
  },
];
